### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by ntlhui** [ntlhui/pyChargeNumberTracker#2]
```
python ./chargeNumberTracker.py
Traceback (most recent call last):
  File "./chargeNumberTracker.py", line 283, in <module>
    root = ChargeNumberTrackerApp()
  File "./chargeNumberTracker.py", line 262, in __init__
    self.tracker.__enter__()
  File "./chargeNumberTracker.py", line 59, in __enter__
    self.dailyHours, self.projects, self.timeRecord, self.prevTime = dataStore.fromDict(data)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by ntlhui** [comment]
3304b0b
