### ISSUE TITLE
Fail to update backups

### ISSUE THREAD

**Issue by ntlhui** [ntlhui/pyChargeNumberTracker#8]
```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\nhui\AppData\Local\Continuum\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "chargeNumberTracker.py", line 637, in destroy
    self.tracker.__exit__(None, None, None)
  File "chargeNumberTracker.py", line 92, in __exit__
    self.flush()
  File "chargeNumberTracker.py", line 107, in flush
    os.rename(self.path, "%s.%d" % (self.path, 0))
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.\\.chargeNumber\\data.json' -> '.\\.chargeNumber\\data.json.0'```
fail on initial close

**Comment by ntlhui** [comment]
Unable to replicate
