### ISSUE TITLE
Log Hours Fail

### ISSUE THREAD

**Issue by ntlhui** [ntlhui/pyChargeNumberTracker#9]
```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\nhui\AppData\Local\Continuum\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "chargeNumberTracker.py", line 630, in logHours
    subprocess.Popen(shlex.split(excPath, posix=False))
  File "C:\Users\nhui\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nhui\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application```
Default json with sample path

**Comment by ntlhui** [comment]
Need to add `shell=True` in Popen
